name: Deploy to production
on:
  workflow_dispatch:
    inputs:
      deploy_commit:
        description: 'Git commit-ish to deploy'
        required: true
        default: 'master'

jobs:
  production_deploy:

    # This is a manually triggered workflow to deploy to production
    # Runs from production branch
    # Do deploy
    # Log deploy
    # Merge with master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # fetch full history
        fetch-depth: 0
        ref: ${{ github.event.inputs.deploy_commit }}

    - name: Make Docker image name available for following steps
      id: tagged_image
      run: |
        echo ::set-output name=value::merkely/loancalculator:$(git log -1 --pretty=%h)


    - env:
        TAGGED_IMAGE: ${{ steps.tagged_image.outputs.value }}
        MERKELY_FINGERPRINT: docker://${TAGGED_IMAGE}
        MERKELY_DESCRIPTION: "Deployed to ${MERKELY_ENVIRONMENT} in pipeline"
        MERKELY_ENVIRONMENT: production
        MERKELY_CI_BUILD_URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
        MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
      run: |
        make docker_pull
        make merkely_control_deployment
        echo YOUR DEPLOYMENT COMMAND HERE

        export MERKELY_DESCRIPTION="Deployed to production in CI by ${GITHUB_ACTOR}"
        make merkely_log_deployment
        git checkout --track origin/production
        git merge ${{ github.event.inputs.deploy_commit }}
        git push origin production



