# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Docker Image
        env:
          DOCKER_DEPLOY_TOKEN: ${{ secrets.DOCKER_DEPLOY_TOKEN }}
          DOCKER_DEPLOY_USERNAME: ${{ secrets.DOCKER_DEPLOY_USERNAME }}
          MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
          MERKELY_ARTIFACT_GIT_URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
          MERKELY_ARTIFACT_GIT_COMMIT: ${GITHUB_SHA}
          MERKELY_CI_BUILD_URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          MERKELY_CI_BUILD_NUMBER: ${GITHUB_RUN_ID}
        run: |
          make build
          make docker_login
          make docker_push
          make merkely_declare_pipeline
          make merkely_log_artifact

      - name: Run test suite
        env:
          MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
          MERKELY_CI_BUILD_URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          MERKELY_TEST_TYPE: unit_test
          MERKELY_TEST_RESULTS: build/test/pytest_unit.xml
        run: |
          make test
          make merkely_log_test

      - name: Run security analysis
        env:
          MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
          MERKELY_CI_BUILD_URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          MERKELY_TEST_TYPE: security
          MERKELY_TEST_RESULTS: build/security/security.xml
        run: |
          make security
          make merkely_log_test

      - name: Run coverage
        env:
          MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
          MERKELY_CI_BUILD_URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          MERKELY_TEST_TYPE: coverage
        run: |
          make coverage
          source build/coverage/coverage_summary.sh
          export COVERAGE_SUMMARY=$COVERAGE_SUMMARY
          make merkely_log_coverage

      - name: Deploy to STAGE
        env:
          MERKELY_API_TOKEN: ${{ secrets.MERKELY_API_TOKEN }}
          MERKELY_CI_BUILD_URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          MERKELY_ENVIRONMENT: staging
          MERKELY_DESCRIPTION: "Deployed to ${MERKELY_ENVIRONMENT} in pipeline"
        run: |
          echo YOUR DEPLOYMENT COMMAND HERE
          make merkely_log_deployment
